### ISSUE TITLE
TileServer

### ISSUE THREAD

**Issue by meshwara** [kartoza/docker-osm#136]
Please forgive me if this question sounds somewhat stupid, but I'm a bit confused. After successfully running this Docker, how can I establish a connection to the tile server ? Or how to connect to this osm using leaflet ? Please enlighten me

**Comment by Gustry** [comment]
There isn't any tile server provided in this docker stack and it's not the purpose.
Only vector data can be fetched, because it's stored in a PostGIS database.

For leaflet, you can use GeoJSON to get vector data and display it in a leaflet map.

If you want tiles, then you should add it yourself, using the vector data stored in this PostGIS database to serve raster data.

I'm closing because it's out of scope in this project, but feel free to continue.

**Comment by Gustry** [comment]
I'm sorry, I forgot there is a QGIS server image provided in the docker stack. (which is different than a tile server that's I forgot about it).

So you can access to raster according to the QGIS project provided : 
* https://github.com/kartoza/docker-osm/blob/develop/docker-compose.web.yml#L16
